spring.application.name=Security-Demo

spring.security.user.password=demo@123
spring.security.user.name=admin

spring.h2.console.enabled=true
spring.datasource.url= jdbc:h2:mem:test

spring.app.jwtSecret=mySecretKey123912738wrtwt5srgaerghwyw453rfwf4334sdf
spring.app.jwtExpirationMS=30000000